### ISSUE TITLE
Type Meta Data not work

### ISSUE THREAD

**Issue by mink365** [AustinBrunkhorst/CPP-Reflection#3]
I have read the section of Type Meta Data, but I can't make it work.

Range is inherit from Object, but there are two pure virtual method:

```
        virtual Type GetType(void) const = 0;
        virtual Object *Clone(void) const = 0;
```

so, I can't got a instance of Range

And I can't find any code in the Parser to handle the annotate attribute of libclang

So, I want to know, is the annotate attribute is ready to be use or some code must be modify before I can use it.

Thank's very much

**Comment by AustinBrunkhorst** [comment]
Those snippets were as minimal as possible to portray the concept.

Meta properties need the macro `META_OBJECT` placed somewhere in the class declaration.

For example, a complete example of the range struct would like look this

``` C++
struct Range : public MetaProperty 
{
    META_OBJECT

    float min, max;

    Range(float min, float max) 
        : min( min )
        , max( max ) { }
};
```

This just automatically defines the virtual methods `GetType( )` and `Clone( )` so the type of a virtual base pointer can be correctly be inferred with the `Variant` class.

Hopefully I'll be able update this repository soon to include build-able projects with complete examples. I've already made a ton of changes to the runtime and parser since deploying it in my projects.

**Comment by mink365** [comment]
OK，thank you very much！

发自我的 iPhone
