### ISSUE TITLE
Is this a work-in-progress source?

### ISSUE THREAD

**Issue by ujhazib** [AustinBrunkhorst/CPP-Reflection#5]
It has tons of problems and bugs, this uploaded version is clearly not working. I had to insert a lot of modifications to make it compile and the Meta attributes is still not working as well.

**Comment by AustinBrunkhorst** [comment]
Yep! I decided to put this up earlier in the year as a starting point resource for those interested in the topic. The current state of the repository is definitely riddled with errors and requires some changes to make buildable. I have re-written almost everything since using this directly with the game engine I've been working on for the past year.

I plan to update this repository with those changes, in addition to adding buildable samples and tests. I'll probably do a write up on it as well.
